version = 1

test_patterns = [
  "**/*.spec.ts",
  "**/*.mock.ts",
  "**/*.test.ts"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser", "nodejs"]
  dialect = "typescript"
  style_guide = "standard"

[[analyzers]]
name = "test-coverage"
enabled = true

[[exclude]]
paths = [
  "dist/**",
  "build/**",
  "node_modules/**",
  "**/*.test.ts",
  "**/*.spec.ts",
  "coverage/**",
  ".github/**",
  ".vscode/**",
  "projects/client/.scripts/**",
  "projects/client/.vite/**",
  "**/node_modules/**",
  "**/*.spec.ts",
  "**/*.test.ts",
  "**/*.d.ts",
  "**/test/**",
  "**/tests/**",
  "**/mock/**",
  "**/mocks/**",
  "**/e2e/**",
  "**/i18n/**",
  "**/static/**"
]
