name: Setup Deno Environment
description: Prepares a Deno development environment with caching and dependencies

inputs:
  deno-version:
    description: 'Deno version to install'
    required: false
    default: 'v2.x'

runs:
  using: composite
  steps:
    - name: Secure the Evidence aka Checkout Code
      id: checkout
      uses: actions/checkout@v4

    - name: Summon the Digital Oracle aka Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ inputs.deno-version }}

    - name: Gather the Tools aka Install Dependencies
      shell: bash
      run: 'deno task install'

    - name: Patch Paraglide.js to Disable PostHog Telemetry
      shell: bash
      run: |
        echo "Patching Paraglide.js to disable PostHog telemetry..."

        # Replace the PostHog proxy with a no-op function
        find node_modules/.deno -path "*@inlang/paraglide-js*/dist/index.js" -type f -exec sed -i 's/return capture;/return () => { console.log("· · · No telemetry for you! ¯\\\\_(ツ)_/¯"); return Promise.resolve(); };/g' {} \;

        # Also disable telemetry shutdown to prevent timeout errors
        find node_modules/.deno -path "*@inlang/paraglide-js*/dist/index.js" -type f -exec sed -i 's/telemetry\.shutdown()/console.log("· · · Nothing to shutdown!")/g' {} \;

        echo "Patch applied."
